name: Hugo-Build
on:
  push:
    branches:
      - Hugo
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Install Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-verson: latest
      - name: Hugo Build
        run: hugo
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          # cname: hugo.pilihu.us.kg
